{{- if .Values.storage.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.storage.persistentClaimName | default (include "matrix.fullname" .) }}"
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
spec:
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
{{- end }}
