apiVersion: v2
name: matrix
description: A chart for Matrix.org, includes Synapse, PostgreSQL, and Element.

type: application

version: 1.0.23

# The version of Synapse
appVersion: "1.97.0"

dependencies:
  - name: postgresql
    version: 13.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgres.enabled
  - name: element
    version: "1.0.*"
    repository: https://remram44.github.io/matrix-helm
    condition: element.enabled
